version: '3'

services:
  redis:
    image: bitnami/redis:7.0
    container_name: ${APP_NAME}_redis
    ports:
      - ${REDIS_PORT}:6379

networks:
  default:
    name: ${APP_NAME}_network
    external: false

volumes:
  exclude:
